- include: ./tasks/docker_ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: ./tasks/docker_centos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: "add user to docker group"
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: "install docker-compose"
  command: "pip3 install docker-compose"

- name: "docker service started"
  service:
    name: docker
    state: started
