version: '3'

services:
  provision:
    build: ./
    volumes:
      - ./:/data
      - ./certs/ssh/:/root/.ssh/
    command: /bin/ash /app/provision.sh

  release:
    build: ./
    volumes:
      - ./:/data
      - ./certs/ssh/:/root/.ssh/
    command: /bin/ash /app/deploy.sh
