version: '3'

services:
  postgres:
    image: postgres
    container_name: analytics_postgres
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
    - "5440:5432"

  redis:
    image: redis:6.0.4-alpine
    container_name: analytics_redis
    ports:
      - "6340:6379"
    logging:
      options:
        max-size: "30m"
        max-file: "3"
      driver: "json-file"

  web:
    build: ./web/
    container_name: analytics_web
    ports:
      - 9000:8080
    logging:
      options:
        max-size: "30m"
        max-file: "3"
      driver: "json-file"

  server:
    build: ./
    container_name: analytics_server
    command: /bin/ash
    logging:
      options:
        max-size: "30m"
        max-file: "3"
      driver: "json-file"

  # clickhouse:
  #   image: yandex/clickhouse-server:19.16.19.85
  #   container_name: analytics_clickhouse
  #   ports:
  #     - "8140:8123"

  nsq:
    image: nsqio/nsq:v1.2.0
    container_name: analytics_msq
    ports:
      - "4140:4150"
      - "4141:4151"
